<?php

use Banimark\Laravel\Admin\PanelController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [PanelController::class, 'login'])->name('banimark.admin.login');
Route::post('/login', [PanelController::class, 'doLogin'])->name('banimark.admin.login.post');
Route::get('/login/2fa', [PanelController::class, 'login2fa'])->name('banimark.admin.login.2fa');
Route::post('/login/2fa', [PanelController::class, 'doLogin2fa'])->name('banimark.admin.login.2fa.post');
Route::get('/security', [PanelController::class, 'security'])->name('banimark.admin.security');
Route::post('/security/begin', [PanelController::class, 'securityBegin'])->name('banimark.admin.security.begin');
Route::post('/security/confirm', [PanelController::class, 'securityConfirm'])->name('banimark.admin.security.confirm');
Route::post('/security/disable', [PanelController::class, 'securityDisable'])->name('banimark.admin.security.disable');
Route::get('/events', [PanelController::class, 'events'])->name('banimark.admin.events');
Route::post('/quick-replies', [PanelController::class, 'saveQuickReplies'])->name('banimark.admin.quick.save');
Route::post('/logout', [PanelController::class, 'logout'])->name('banimark.admin.logout');
Route::get('/', [PanelController::class, 'dashboard'])->name('banimark.admin.dashboard');
Route::get('/inbox', [PanelController::class, 'inbox'])->name('banimark.admin.inbox');
Route::get('/staff', [PanelController::class, 'agents'])->name('banimark.admin.agents');
Route::post('/staff', [PanelController::class, 'saveAgent'])->name('banimark.admin.agents.save');
Route::post('/staff/delete', [PanelController::class, 'deleteAgent'])->name('banimark.admin.agents.delete');
Route::post('/staff/2fa-reset', [PanelController::class, 'staffTotpReset'])->name('banimark.admin.agents.totp.reset');
Route::post('/staff/2fa-require', [PanelController::class, 'staffTotpRequire'])->name('banimark.admin.agents.totp.require');
Route::get('/escalation', [PanelController::class, 'escalation'])->name('banimark.admin.escalation');
Route::post('/escalation', [PanelController::class, 'saveEscalation'])->name('banimark.admin.escalation.save');
Route::post('/escalation/test', [PanelController::class, 'testEmail'])->name('banimark.admin.escalation.test');
Route::get('/conversation/{sessionId}', [PanelController::class, 'conversation'])->name('banimark.admin.conversation');
Route::get('/conversation/{sessionId}/messages', [PanelController::class, 'messages'])->name('banimark.admin.conversation.messages');
Route::post('/conversation/{sessionId}/reply', [PanelController::class, 'reply'])->name('banimark.admin.conversation.reply');
Route::post('/conversation/{sessionId}/mode', [PanelController::class, 'setMode'])->name('banimark.admin.conversation.mode');
Route::get('/providers', [PanelController::class, 'providers'])->name('banimark.admin.providers');
Route::post('/providers', [PanelController::class, 'saveProvider'])->name('banimark.admin.providers.save');
Route::post('/providers/delete', [PanelController::class, 'deleteProvider'])->name('banimark.admin.providers.delete');
Route::get('/rules', [PanelController::class, 'rules'])->name('banimark.admin.rules');
Route::post('/rules', [PanelController::class, 'saveRule'])->name('banimark.admin.rules.save');
Route::post('/rules/delete', [PanelController::class, 'deleteRule'])->name('banimark.admin.rules.delete');
Route::post('/rules/move', [PanelController::class, 'moveRule'])->name('banimark.admin.rules.move');
Route::post('/rules/folder', [PanelController::class, 'saveFolder'])->name('banimark.admin.rules.folder');
Route::post('/rules/folder/delete', [PanelController::class, 'deleteFolder'])->name('banimark.admin.rules.folder.delete');
Route::post('/rules/folder/move', [PanelController::class, 'moveFolder'])->name('banimark.admin.rules.folder.move');
Route::get('/tools', [PanelController::class, 'tools'])->name('banimark.admin.tools');
Route::get('/tools/schema', [PanelController::class, 'toolSchema'])->name('banimark.admin.tools.schema');
Route::post('/tools', [PanelController::class, 'saveTool'])->name('banimark.admin.tools.save');
Route::post('/tools/delete', [PanelController::class, 'deleteTool'])->name('banimark.admin.tools.delete');
Route::get('/widget', [PanelController::class, 'widget'])->name('banimark.admin.widget');
Route::get('/changelog', [PanelController::class, 'changelog'])->name('banimark.admin.changelog');
Route::get('/license', [PanelController::class, 'license'])->name('banimark.admin.license');
Route::post('/license', [PanelController::class, 'saveLicense'])->name('banimark.admin.license.save');
Route::post('/widget', [PanelController::class, 'saveWidget'])->name('banimark.admin.widget.save');
